name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - feature/*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22
      
      # step 3: permission
      - name: Grant execute permission for jest
        run: chmod +x ./node_modules/.bin/jest

      # Step 4: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 5: Run unit tests
      - name: Run unit tests
        run: npm test

      # Step 6: Lint the code
      - name: Lint code
        run: npm run lint

      # Step 7: Simulate deployment
      - name: Deploy to staging
        if: success()
        run: echo "Deployed to staging environment successfully!"

